### ISSUE TITLE
Workspace files for working on the project

### ISSUE THREAD

**Issue by rvangraan** [bdbergeron/BDBOAuth1Manager#29]
Hi there,

I would like to enhance the project in a few ways, but I noticed that there isn't any workspace/project files included. Can you please add them so that it is easy to work on the project?

Thanks,
Rudolph

**Comment by kolpanic** [comment]
FWIW, there are project files in [BDBOAuth1ManagerDemo](/bdbergeron/BDBOAuth1Manager/tree/master/BDBOAuth1ManagerDemo).

**Comment by bdbergeron** [comment]
As @kolpanic stated, there are project files within the demo folder. If you're looking for something different, please let me know. For now, I'm marking this issue as closed.
