### ISSUE TITLE
How can i use this with 2 legged oauth authentication?

### ISSUE THREAD

**Issue by hardikamal** [bdbergeron/BDBOAuth1Manager#32]
How can i use this with 2 legged oauth authentication....my api call are from drupal webservices...can i get an idea how to use this with drupal api where i only need consumer key and consumer secret to authenticate the user for api access......Thanks

**Comment by bdbergeron** [comment]
Take a look at issue https://github.com/bdbergeron/BDBOAuth1Manager/issues/19#issuecomment-47815501.

**Comment by hardikamal** [comment]
@bdbergeron  Thanks Solved
