### ISSUE TITLE
Unauthorized when upload file

### ISSUE THREAD

**Issue by Stefanus-Januar** [bdbergeron/BDBOAuth1Manager#38]
Hi, I'm trying to migrate the old code from RSOAuthEngine to BDBOAuth1Manager (1.5.0). The migration run smoothly with login, logout, POST, and GET. 

The problem comes when I try to upload image to the server and get Request failed: unauthorized (401).

```
NSURLSessionDataTask *task = [_networkManager POST:URLString parameters:parameters constructingBodyWithBlock:^(id<AFMultipartFormData> formData) {
        
        [formData appendPartWithFormData:imagedata name:imagekey];
        
    } success:^(NSURLSessionDataTask *task, id responseObject) {

        // Success 

    } failure:^(NSURLSessionDataTask *task, NSError *error) {
        
       // Fail
    }];
```

**Comment by kolpanic** [comment]
@Stefanus-Januar Are you using AFNetworking 2.6, and do your parameters include values with slashes? If so, it may be related to #36.

**Comment by Stefanus-Januar** [comment]
Hi @kolpanic thx for your reply. I think it's a different issue because the parameters is nil. I also have tried with AFNetworking 2.6 and BDBOAuth1Manager (latest commit) but still get same error.

If somebody has sample project with upload file, it will help a lot.

Here is the input : 

```
URLString : "https://www.kaskus.co.id/api/oauth/image"
parameters : nil
imagedata : (NSData)
imagekey : "image"
```

**Comment by Stefanus-Januar** [comment]
After investigation,finally I found MKNetworkit used fileName "file" as default.

So I change my code and it works.
````
 [formData appendPartWithFileData:imagedata name:imagekey fileName:@"file" mimeType:@"application/octet-stream"];
````
