### ISSUE TITLE
Podspec update?

### ISSUE THREAD

**Issue by strefethen** [bdbergeron/BDBOAuth1Manager#41]
The current Cocoapod is fixed on AFNetworking 2.5.0 and I was curious if you had plan to push the updated podspec? We're using the BDBOAuth1Manager Coacopod and the v2.50 dependency locks us on that version. Not a huge issue and we can work around it but curious nonetheless. I'm assuming you are maintaining the podspec which may be a poor assumption.

**Comment by chrisdhaan** [comment]
Are there plans to release a new version with AFNetworking 2.6.0 in the pod spec?

**Comment by bdbergeron** [comment]
Hi guys. Sorry for the delay in getting the podspec updated; I had actually committed the update to AFNetworking 2.6.0 a few weeks back, but never updated the spec. You should be all good to go now.

**Comment by strefethen** [comment]
@bdbergeron thanks much!
