### ISSUE TITLE
Where is BDBOAuth1RequestOperationManager?

### ISSUE THREAD

**Issue by GlitchEclipse** [bdbergeron/BDBOAuth1Manager#47]
This class is not included the pod anymore.

**Comment by bdbergeron** [comment]
BDBOAuth1RequestOperationManager was a subclass of AFHTTPRequestOperationManager, which used the old NSURLConnection APIs and frameworks. AFNetworking removed support for NSURLConnection-based APIs in version 3.x, which is used by version 2.x of this library. ([AFNetworking 3.0.0 release notes](https://github.com/AFNetworking/AFNetworking/releases/tag/3.0.0), [PR](https://github.com/AFNetworking/AFNetworking/issues/3120)) If you need support for NSURLConnection-based APIs (including BDBOAuth1RequestOperationManager), you'll have to use AFNetworking 2.x and version 1.x of this library.
